=== codecandiescom/powertweak-0.99.5/xml/pci/pci.dtd
<!ELEMENT DEVICE ANY>
<!ELEMENT REGISTER (FRAME?,COMBO?,GROUP?,(BITMASK,(ONBITS,OFFBITS)?)?,TYPE,LOW?,HIGH?,WIDGETTEXT,(DESCRIPTION,CONFIGNAME)?)>

<!ELEMENT FRAME (#PCDATA)>
<!ELEMENT COMBO (#PCDATA)>
<!ELEMENT GROUP (#PCDATA)>

<!ELEMENT BITMASK (#PCDATA)>
<!ELEMENT ONBITS (#PCDATA)>
<!ELEMENT OFFBITS (#PCDATA)>

<!ELEMENT WIDGETTEXT (#PCDATA)>
<!ELEMENT CONFIGNAME (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT LOW (#PCDATA)>
<!ELEMENT HIGH (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>

<!ATTLIST DEVICE
vendor	CDATA	#REQUIRED
id	CDATA #REQUIRED
>

<!ATTLIST REGISTER
base	CDATA	#REQUIRED
bit	CDATA	#IMPLIED
>

=== codecandiescom/powertweak-0.99.5/xml/pci/Intel/82437-VX.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x8086" id="0x7030">
	<REGISTER base="0x4f" bit="3">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU Priority</WIDGETTEXT>
	<DESCRIPTION>Enabling this tweak gives the CPU the PCI bus after
two PCI slots as opposed to after three slots.</DESCRIPTION>
	<CONFIGNAME>CPU_PRIORITY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x50" bit="3">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI concurrency</WIDGETTEXT>
	<DESCRIPTION>Enable this to allow CPU to access DRAM and L2 cache
while a non-PIIX3 PCI master is targeting peer devices.</DESCRIPTION>
	<CONFIGNAME>PCI_CONCURRENCY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x52">
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000001</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>First level cache enable</WIDGETTEXT>
	<DESCRIPTION>This enables the level 1 cache.</DESCRIPTION>
	<CONFIGNAME>L1_CACHE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x53">
	<BITMASK>00011111</BITMASK>
	<TYPE>Slider</TYPE>
	<LOW>4</LOW>
	<HIGH>31</HIGH>
	<WIDGETTEXT>DRAM Cache refresh timer.</WIDGETTEXT>
	<DESCRIPTION>Sets the refresh rate of the DRAM cache</DESCRIPTION>
	<CONFIGNAME>DRAM_CACHE_REFRESH_TIMER</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x55">
	<BITMASK>00011000</BITMASK>
	<ONBITS> 00011000</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast RAM timings.</WIDGETTEXT>
	<DESCRIPTION>Enable this to set CAS# latency to 2 cycles as
opposed to 3 cycles. Also controls the RAS# precharge, RAS# active
to precharge time, and Refresh to RAS# active delay. Enabled=3,4,7
as opposed to 3,5,8.</DESCRIPTION>
	<CONFIGNAME>FAST_RAM_TIMINGS</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x56" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Refresh RAS# assertion</WIDGETTEXT>
	<DESCRIPTION>Enabled=5 clocks, disabled=4 clocks</DESCRIPTION>
	<CONFIGNAME>REFRESH_RAS_ASSERTION</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast MA to RAS# delay</WIDGETTEXT>
	<DESCRIPTION>Enabled=1 clock, Disabled=2 clocks.</DESCRIPTION>
	<CONFIGNAME>FAST_MA_TO_RAS_DELAY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast RAS to CAS delay</WIDGETTEXT>
	<DESCRIPTION>Enabled=2 clock, Disabled=3 clocks.
The slower timing may be required to support system designs with
longer trace lengths or slower memories.</DESCRIPTION>
	<CONFIGNAME>FAST_MA_TO_RAS_DELAY</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/Intel/82439-TX.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x8086" id="0x7100">

	<REGISTER base="0x50" bit="3">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI concurrency</WIDGETTEXT>
	<DESCRIPTION>Enable this to allow CPU to access DRAM and L2 cache
while a non-PIIX3 PCI master is targeting peer devices.</DESCRIPTION>
	<CONFIGNAME>PCI_CONCURRENCY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x52">
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000010</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>First level cache enable</WIDGETTEXT>
	<DESCRIPTION>This enables the level 1 cache.</DESCRIPTION>
	<CONFIGNAME>L1_CACHE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x53">
	<BITMASK>00011111</BITMASK>
	<TYPE>Slider</TYPE>
	<LOW>4</LOW>
	<HIGH>31</HIGH>
	<WIDGETTEXT>DRAM Cache refresh timer.</WIDGETTEXT>
	<DESCRIPTION>This timer determines the time the MXTC remains idle
during a DRAM cache refresh sequence.</DESCRIPTION>
	<CONFIGNAME>DRAM_CACHE_REFRESH_TIMER</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x55" bit="4">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CAS# Latency</WIDGETTEXT>
	<DESCRIPTION>Enable this to set CAS# latency to 2 cycles as
opposed to 3 cycles. Note, that if you leave this disabled,
you should also set RAS# timing to disabled.</DESCRIPTION>
	<CONFIGNAME>CAS_LATENCY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x55" bit="3">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>RAS# timing</WIDGETTEXT>
	<DESCRIPTION>This tweak controls the RAS# precharge, RAS# active
to precharge time, and Refresh to RAS# active delay. Enabled=3,4,7
as opposed to 3,5,8. If you enable this bit, you should also enable
the CAS# latency tweak above.</DESCRIPTION>
	<CONFIGNAME>RAS_TIMING</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x56" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Refresh RAS# assertion</WIDGETTEXT>
	<DESCRIPTION>Enabled=5 clocks, disabled=4 clocks</DESCRIPTION>
	<CONFIGNAME>REFRESH_RAS_ASSERTION</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast MA to RAS# delay</WIDGETTEXT>
	<DESCRIPTION>Enabled=1 clock, Disabled=2 clocks.</DESCRIPTION>
	<CONFIGNAME>FAST_MA_TO_RAS_DELAY</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/VIA/82C586-0.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1106" id="0x0586">
	<REGISTER base="0x40" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>ISA command delay</WIDGETTEXT>
	<DESCRIPTION>ISA command delay</DESCRIPTION>
	<CONFIGNAME>ISA_COMMAND_DELAY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Extended ISA bus ready</WIDGETTEXT>
	<DESCRIPTION>Extended ISA bus ready</DESCRIPTION>
	<CONFIGNAME>EXTENDED_ISA_READY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="5">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>4 waitstate ISA SLAVE I/O</WIDGETTEXT>
	<DESCRIPTION>Use 4 waitstates instead of 5 for ISA SLAVE</DESCRIPTION>
	<CONFIGNAME>ISA_SLAVE_WS</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="4">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>2 Waitstate chipset I/O</WIDGETTEXT>
	<DESCRIPTION>Use 2 waitstates instead of 4 for chipset I/O</DESCRIPTION>
	<CONFIGNAME>CHIPSET_IO_WS</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="3">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Disable Extended IO recovery time</WIDGETTEXT>
	<DESCRIPTION>Disable extended IO recovery time</DESCRIPTION>
	<CONFIGNAME>IO_RECOVERY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Extend ALE</WIDGETTEXT>
	<DESCRIPTION>Extend ALE</DESCRIPTION>
	<CONFIGNAME>EXTEND_ALE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>0 wait states ROM reads</WIDGETTEXT>
	<DESCRIPTION>Use 0 wait states instead of 1 for ROM reads</DESCRIPTION>
	<CONFIGNAME>ROM_WS</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x46" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Disallow PCI burst read interrupting</WIDGETTEXT>
	<DESCRIPTION>Don't allow PCI burst reads to be interrupted</DESCRIPTION>
	<CONFIGNAME>PCI_BURST_INTERRUPTING</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x46" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Post memory write enable</WIDGETTEXT>
	<DESCRIPTION>Post memory write enable</DESCRIPTION>
	<CONFIGNAME>POST_MEM_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x47" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI delayed transactions</WIDGETTEXT>
	<DESCRIPTION>PCI delayed transactions</DESCRIPTION>
	<CONFIGNAME>PCI_DELAY_TRANSACTIONS</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x47" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Disable write delay transaction timeout timer</WIDGETTEXT>
	<DESCRIPTION>Disable write delay transaction timeout timer</DESCRIPTION>
	<CONFIGNAME>WR_DELAY_TRANSACTION_TO</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x47" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Disable read delay transaction timeout timer</WIDGETTEXT>
	<DESCRIPTION>Disable read delay transaction timeout timer</DESCRIPTION>
	<CONFIGNAME>RD_DELAY_TRANSACTION_TO</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/Intel/82434.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x8086" id="0x04A3">
	<REGISTER base="0x08" bit="4">
	<TYPE>InfoBool</TYPE>
	<WIDGETTEXT>Chipset type</WIDGETTEXT>
	<DESCRIPTION>Set indicates a 82434NX chipset, 82434LX otherwise.</DESCRIPTION>
	</REGISTER>

	<REGISTER base="0x53" bit="3">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Read-around-write enable</WIDGETTEXT>
	<DESCRIPTION>If enabled, the chipset, during a CPU read cycle to
memory where posted write cycles are pending, internally snoops the write
buffers. If the address of the read differs from the posted write
addresses, the chipset initiates the memory read cycle ahead of the
pending posted memory write. When zero, the pending posted write is
written to memory before the memory read is performed. When one, the
chipset initiates the memory read ahead of the pending posted memory
writes.</DESCRIPTION>
	<CONFIGNAME>READ_AROUND_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x53" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU->PCI posted write</WIDGETTEXT>
	<DESCRIPTION>Enables CPU->PCI write posting.</DESCRIPTION>
	<CONFIGNAME>CPU_PCI_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x53" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU->RAM posted write</WIDGETTEXT>
	<DESCRIPTION>Enables CPU->RAM write posting. For the 82434NX this
setting has no effect (CPU->RAM posting is always enabled).</DESCRIPTION>
	<CONFIGNAME>CPU_RAM_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x54" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI->RAM posted write</WIDGETTEXT>
	<DESCRIPTION>Enables PCI->RAM write posting.</DESCRIPTION>
	<CONFIGNAME>PCI_RAM_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x54" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI Burst</WIDGETTEXT>
	<DESCRIPTION>Enables PCI Bursting.</DESCRIPTION>
	<CONFIGNAME>PCI_BURST</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x57" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Burst of four refresh</WIDGETTEXT>
	<DESCRIPTION>Enables refreshes in bursts of four, at 1/4 the
frequency of normal refreshes. The chipset defers refreshes to idle
times, if possible.</DESCRIPTION>
	<CONFIGNAME>BURST_OF_FOUR</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x57" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Refresh type</WIDGETTEXT>
	<DESCRIPTION>Enabled for CAS-before-RAS refreshes. Disabled for
RAS-only refreshes.</DESCRIPTION>
	<CONFIGNAME>REFRESH_TYPE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58">
	<TYPE>RadioButton</TYPE>
	<GROUP>DRAMBURST</GROUP>
	<NAME>X-4-4-4</NAME>
	<DESCRIPTION>X-4-4-4 read/write timing. 82434NX only.</DESCRIPTION>
	<BITMASK>01100000</BITMASK>
	<ONBITS> 00000000</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<CONFIGNAME>DRAM_BURST_X444</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58">
	<TYPE>RadioButton</TYPE>
	<GROUP>DRAMBURST</GROUP>
	<NAME>X-4-4-4/X-3-3-3</NAME>
	<DESCRIPTION>X-4-4-4 read/X-3-3-3 write timing. 82434NX only.</DESCRIPTION>
	<BITMASK>01100000</BITMASK>
	<ONBITS> 00100000</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<CONFIGNAME>DRAM_BURST_X444_X333</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58">
	<TYPE>RadioButton</TYPE>
	<GROUP>DRAMBURST</GROUP>
	<NAME>X-3-3-3</NAME>
	<DESCRIPTION>X-3-3-3 read/write timing. 82434NX only.</DESCRIPTION>
	<BITMASK>01100000</BITMASK>
	<ONBITS> 01100000</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<CONFIGNAME>DRAM_BURST_X333</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>RAS wait state</WIDGETTEXT>
	<DESCRIPTION>When enabled, adds an additional wait state before RAS
assertion.</DESCRIPTION>
	<CONFIGNAME>RAS_WAIT_STATES</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CAS wait state</WIDGETTEXT>
	<DESCRIPTION>When enabled, adds an additional wait state before CAS
assertion but only during the first CAS assertion of a burst cycle.
Typically enabled at 66MHz and disabled at 60MHz.</DESCRIPTION>
	<CONFIGNAME>RAS_WAIT_STATES</CONFIGNAME>
	</REGISTER>
</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/VIA/82C598-1.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1106" id="0x8598">

	<REGISTER base="0x40" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP posted write</WIDGETTEXT>
	<DESCRIPTION>Enables write posting to the AGP bus</DESCRIPTION>
	<CONFIGNAME>AGP_POSTED_WR</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP dynamic burst</WIDGETTEXT>
	<DESCRIPTION>Enables dynamic bursting to the AGP bus</DESCRIPTION>
	<CONFIGNAME>AGP_DYNAMIC_BURST</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="5">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP 1 waitstate burst write</WIDGETTEXT>
	<DESCRIPTION>Enables single waitstate burst writes to the AGP bus</DESCRIPTION>
	<CONFIGNAME>AGP_1WS_BURST_WR</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="4">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP to DRAM prefetch</WIDGETTEXT>
	<DESCRIPTION>Enables prefetching data when fetching textures from main memory</DESCRIPTION>
	<CONFIGNAME>AGP_DRAM_PREFETCH</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="3">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP allowed before CPU->PCI post write not flushed</WIDGETTEXT>
	<DESCRIPTION>Enables this tweak means that AGP transactions can occur before waiting for
writes from the CPU to other PCI devices have finished.</DESCRIPTION>
	<CONFIGNAME>AGP_BEFORE_CPU_TO_PCI_POST_WRITE_FLUSH</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP Master read caching</WIDGETTEXT>
	<DESCRIPTION>Enables read caching on AGP bus.</DESCRIPTION>
	<CONFIGNAME>AGP_MASTER_RD_CACHING</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP delayed transactions</WIDGETTEXT>
	<DESCRIPTION>Enables delayed transactions on the AGP bus.</DESCRIPTION>
	<CONFIGNAME>AGP_DELAY_TRANSACTIONS</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x41" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU backoff on AGP read retry timeout</WIDGETTEXT>
	<DESCRIPTION>Tells CPU to wait if AGP bus fails to read from DRAM.</DESCRIPTION>
	<CONFIGNAME>AGP_CPU_BACKOFF_TIMEOUT</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x41" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU to AGP I/O write posting</WIDGETTEXT>
	<DESCRIPTION>Enables posted writes when performing AGP I/O.</DESCRIPTION>
	<CONFIGNAME>CPU_TO_AGP_POSTED_WRITE_IO</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Read prefetch for enhance command</WIDGETTEXT>
	<DESCRIPTION>When enabled, the AGP controller will only prefetch if an enhance
command occurs. When disabled, it always performs prefetch.</DESCRIPTION>
	<CONFIGNAME>AGP_PREFETCH_ONLY_ENHANCE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP master 1 waitstate write</WIDGETTEXT>
	<DESCRIPTION>Enables single waitstate writes to the AGP bus.</DESCRIPTION>
	<CONFIGNAME>AGP_MASTER_1WS_WR</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="5">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP master 1 waitstate read</WIDGETTEXT>
	<DESCRIPTION>Enables single waitstate reads from the AGP bus.</DESCRIPTION>
	<CONFIGNAME>AGP_MASTER_1WS_RD</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="4">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Extend AGP master for efficient dummy req cycles</WIDGETTEXT>
	<DESCRIPTION>Enables more efficient generation of dummy request cycles across the AGP bus.</DESCRIPTION>
	<CONFIGNAME>AGP_EFFICIENT_DUMMY_CYCLES</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="3">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP write timeout asserts #STOP</WIDGETTEXT>
	<DESCRIPTION>The #STOP line is asserted when a write timeout occurs.
Enabling this setting greatly improves the performance on some BTTV capture cards.</DESCRIPTION>
	<CONFIGNAME>AGP_WR_TIMEOUT_STOP</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP read timeout asserts #STOP</WIDGETTEXT>
	<DESCRIPTION>The #STOP line is asserted when a read timeout occurs.</DESCRIPTION>
	<CONFIGNAME>AGP_RD_TIMEOUT_STOP</CONFIGNAME>
	</REGISTER>

</DEVICE>
