=== codecandiescom/powertweak-0.99.5/xml/pci/pci.dtd
<!ELEMENT DEVICE ANY>
<!ELEMENT REGISTER (FRAME?,COMBO?,GROUP?,(BITMASK,(ONBITS,OFFBITS)?)?,TYPE,LOW?,HIGH?,WIDGETTEXT,(DESCRIPTION,CONFIGNAME)?)>

<!ELEMENT FRAME (#PCDATA)>
<!ELEMENT COMBO (#PCDATA)>
<!ELEMENT GROUP (#PCDATA)>

<!ELEMENT BITMASK (#PCDATA)>
<!ELEMENT ONBITS (#PCDATA)>
<!ELEMENT OFFBITS (#PCDATA)>

<!ELEMENT WIDGETTEXT (#PCDATA)>
<!ELEMENT CONFIGNAME (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT LOW (#PCDATA)>
<!ELEMENT HIGH (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>

<!ATTLIST DEVICE
vendor	CDATA	#REQUIRED
id	CDATA #REQUIRED
>

<!ATTLIST REGISTER
base	CDATA	#REQUIRED
bit	CDATA	#IMPLIED
>

=== codecandiescom/powertweak-0.99.5/xml/pci/ALI/M1541.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x10b9" id="0x1541">
	<REGISTER base="0x40" bit="4">
	<FRAME>Cache features</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>K6 Write Allocate</WIDGETTEXT>
	<DESCRIPTION>Check this if you want to enable the "Write Allocate"
feature	of the K6 processors. Write Allocate will enhance system
performance by clustering memory accesses.
</DESCRIPTION>
	<CONFIGNAME>WRITE_ALLOCATE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="3">
	<FRAME>Cache features</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Cyrix Linear Burst</WIDGETTEXT>
	<DESCRIPTION>Check this if you want to enable the "Linear Burst"
feature	of the Cyrix M1/M2 processors. Linear Burst will enhance system
performance by clustering memory accesses.
</DESCRIPTION>
	<CONFIGNAME>LINEAR_BURST</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x89">
	<FRAME>PCI bus</FRAME>
	<TYPE>Slider</TYPE>
	<LOW>0</LOW>
	<HIGH>255</HIGH>
	<WIDGETTEXT>Minimum PCI33 slice on PCI33 bus</WIDGETTEXT>
	<DESCRIPTION>This number controls the minimum number of
PCI bus cycles a device gets. If the device wants the bus longer, 
it might be interrupted. Setting this to a higher value increases
throughput but decreases latency. Setting this to low might be dangerous
as some PCI chips (Compaq) have a bug when interrupted.
</DESCRIPTION>
	<CONFIGNAME>PCI_SLICE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x8A">
	<FRAME>PCI bus</FRAME>
	<TYPE>Slider</TYPE>
	<LOW>0</LOW>
	<HIGH>255</HIGH>
	<WIDGETTEXT>Minimum CPU slice on PCI33 bus</WIDGETTEXT>
	<DESCRIPTION>This number controls the minimum number of
PCI33 bus cycles the CPU gets. If the CPU  wants the bus longer, 
it might be interrupted. Setting this to a higher value increases
throughput but decreases latency. 
</DESCRIPTION>
	<CONFIGNAME>CPU_SLICE</CONFIGNAME>
	</REGISTER>


</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/DEC/21050.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1011" id="0x0001">
	<REGISTER base="0x53" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU to PCI posted write</WIDGETTEXT>
	<DESCRIPTION>Enables write-behind semantics for PCI devices.
</DESCRIPTION>
	<CONFIGNAME>CPU_TO_PCI_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x53" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU to RAM posted write</WIDGETTEXT>
	<DESCRIPTION>Enables write-behind semantics for CPU->RAM.
</DESCRIPTION>
	<CONFIGNAME>CPU_TO_RAM_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x54" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI to RAM posted write</WIDGETTEXT>
	<DESCRIPTION>Enables write-behind semantics for PCI devices.
</DESCRIPTION>
	<CONFIGNAME>PCI_TO_RAM_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x54" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI burst</WIDGETTEXT>
	<DESCRIPTION>Enables burst transfers.
</DESCRIPTION>
	<CONFIGNAME>PCI_BURST</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/VIA/82C586-1.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1106" id="0x0571">

	<REGISTER base="0x41" bit="7">
	<FRAME>IDE Controller tweaks</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>IDE 0 prefetch</WIDGETTEXT>
	<DESCRIPTION>Enables read prefetch on primary IDE bus</DESCRIPTION>
	<CONFIGNAME>IDE0_PREFETCH</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x41" bit="6">
	<FRAME>IDE Controller tweaks</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>IDE 0 posted writes</WIDGETTEXT>
	<DESCRIPTION>Enables delayed writes on primary IDE bus</DESCRIPTION>
	<CONFIGNAME>IDE0_POST_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x41" bit="5">
	<FRAME>IDE Controller tweaks</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>IDE 1 prefetch</WIDGETTEXT>
	<DESCRIPTION>Enables read prefetch on secondary IDE bus</DESCRIPTION>
	<CONFIGNAME>IDE1_PREFETCH</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x41" bit="4">
	<FRAME>IDE Controller tweaks</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>IDE 1 posted writes</WIDGETTEXT>
	<DESCRIPTION>Enables delayed writes on secondary IDE bus</DESCRIPTION>
	<CONFIGNAME>IDE1_POST_WRITE</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/VIA/82C691.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1106" id="0x0691">

	<REGISTER base="0x51" bit="2">
	<FRAME>Host CPU protocol</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>4-level prefetch buffer</WIDGETTEXT>
	<DESCRIPTION>This option increases the buffer-depth for prefetches
from 1 to 4, giving higher throughput.</DESCRIPTION>
	<CONFIGNAME>CPU_PREFETCH_BUFFER</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x51" bit="1">
	<FRAME>Host CPU protocol</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>4-level write buffer</WIDGETTEXT>
	<DESCRIPTION>This option increases the buffer-depth for writes
from 1 to 4, giving higher throughput.</DESCRIPTION>
	<CONFIGNAME>CPU_WRITE_BUFFER</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x71" bit="7">
	<FRAME>PCI Bus behavior</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Dynamic Burst</WIDGETTEXT>
	<DESCRIPTION>This option enables automatic detection of PCI bursts.
This is often the optimal setting.</DESCRIPTION>
	<CONFIGNAME>DYNAMIC_BURST</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x71" bit="3">
	<FRAME>PCI Bus behavior</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI Burst</WIDGETTEXT>
	<DESCRIPTION>This option forces all PCI transaction to be bursts.
This option has no effect if Dynamic Burst is enabled.</DESCRIPTION>
	<CONFIGNAME>FORCE_BURST</CONFIGNAME>
	</REGISTER>

<!--
// This set of tweaks disabled for now.
These tweaks should be tristate rather than boolean.

00-none
01-2 way interleave
10-4 way interleave
11-invalid

	<REGISTER base="0x64">
	<FRAME>Memory Interleave settings</FRAME>
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000001</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Bank 0/1 interleaving 2x</WIDGETTEXT>
	<DESCRIPTION>Enable Memory interleaving. This is known to
improve memory throughput by 20% on some sytems.</DESCRIPTION>
	<CONFIGNAME>BANK1_INTERLEAVE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x65">
	<FRAME>Memory Interleave settings</FRAME>
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000001</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Bank 2/3 interleaving 2x</WIDGETTEXT>
	<DESCRIPTION>Enable Memory interleaving. This is known to
improve memory throughput by 20% on some sytems.</DESCRIPTION>
	<CONFIGNAME>BANK2_INTERLEAVE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x66">
	<FRAME>Memory Interleave settings</FRAME>
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000001</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Bank 4/5 interleaving 2x</WIDGETTEXT>
	<DESCRIPTION>Enable Memory interleaving. This is known to
improve memory throughput by 20% on some sytems.</DESCRIPTION>
	<CONFIGNAME>BANK3_INTERLEAVE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x67">
	<FRAME>Memory Interleave settings</FRAME>
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000001</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Bank 6/7 interleaving 2x</WIDGETTEXT>
	<DESCRIPTION>Enable Memory interleaving. This is known to
improve memory throughput by 20% on some sytems.</DESCRIPTION>
	<CONFIGNAME>BANK4_INTERLEAVE</CONFIGNAME>
	</REGISTER>
-->

	<REGISTER base="0x68" bit="2">
	<FRAME>DRAM settings</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Burst refresh</WIDGETTEXT>
	<DESCRIPTION>This option enables `bursting' during
refresh cycles. Enabled is faster.</DESCRIPTION>
	<CONFIGNAME>DRAM_BURSTREFRESH</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x68" bit="6">
	<FRAME>DRAM settings</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Allow multiple banks active</WIDGETTEXT>
	<DESCRIPTION>This option allows multiple memory banks to be 
active at the same time. Enabled is faster.</DESCRIPTION>
	<CONFIGNAME>DRAM_MULTIBANK</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/Intel/82371AB-PIIX4-1.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x8086" id="0x7111">

<!--- 82371AB-PIIX4 specification                                     -->
<!--- http://developer.intel.com/design/intarch/datashts/29056201.pdf -->
<!--- ************************************** -->
	<REGISTER base="0x40" bit="0">
	<FRAME>IDE Controller tweaks (primary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast Timing Bank Drive Select 0 (master)</WIDGETTEXT>
	<DESCRIPTION>When TIME0=1, accesses to the data port of the enabled I/O addres range use fast timings.</DESCRIPTION>
	<CONFIGNAME>FAST_TIME_00</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x40" bit="4">
	<FRAME>IDE Controller tweaks (primary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast Timing Bank Drive Select 0 (slave)</WIDGETTEXT>
	<DESCRIPTION>When TIME1=1, accesses to the data port of the enabled I/O addres range use fast timings.</DESCRIPTION>
	<CONFIGNAME>FAST_TIME_01</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="1">
	<FRAME>IDE Controller tweaks (primary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>IORDY sampling primary (master)</WIDGETTEXT>
	<DESCRIPTION>0</DESCRIPTION>
	<CONFIGNAME>IORDY_00</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x40" bit="5">
	<FRAME>IDE Controller tweaks (primary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>IORDY sampling primary (slave)</WIDGETTEXT>
	<DESCRIPTION>0</DESCRIPTION>
	<CONFIGNAME>IORDY_01</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="2">
	<FRAME>IDE Controller tweaks (primary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Primary master prefetch/posting (master)</WIDGETTEXT>
	<DESCRIPTION>When enabled, prefetch and posting to the primary IDE port
is enabled for drive 0</DESCRIPTION>
	<CONFIGNAME>PPE00</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x40" bit="6">
	<FRAME>IDE Controller tweaks (primary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Primary slave prefetch/posting (slave)</WIDGETTEXT>
	<DESCRIPTION>When enabled, prefetch and posting to the primary IDE port
is enabled for drive 1</DESCRIPTION>
	<CONFIGNAME>PPE01</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="3">
	<FRAME>IDE Controller tweaks (primary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>DMA Timing enable Only (master)</WIDGETTEXT>
	<DESCRIPTION>when DTE0=0 DMA and PIO data transfers use the fast timing mode. When DTE0=1 fast timing mode is enabled for DMA transfers. (suggested value 0)</DESCRIPTION>
	<CONFIGNAME>DMA_TIMING_00</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x40" bit="7">
	<FRAME>IDE Controller tweaks (primary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>DMA Timing enable Only (slave)</WIDGETTEXT>
	<DESCRIPTION>when DTE1=0 DMA and PIO data transfers use the fast timing mode. When DTE0=1 fast timing mode is enabled for DMA transfers. (suggested value 0)</DESCRIPTION>
	<CONFIGNAME>DMA_TIMING_01</CONFIGNAME>
	</REGISTER>

<!--- ************************************** -->
	<REGISTER base="0x42" bit="0">
	<FRAME>IDE Controller tweaks (secondary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast Timing Bank Drive Select 0 (master)</WIDGETTEXT>
	<DESCRIPTION>When TIME0=1, accesses to the data port of the enabled I/O addres range use fast timings.</DESCRIPTION>
	<CONFIGNAME>FAST_TIME_10</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x42" bit="4">
	<FRAME>IDE Controller tweaks (secondary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast Timing Bank Drive Select 0 (slave)</WIDGETTEXT>
	<DESCRIPTION>When TIME1=1, accesses to the data port of the enabled I/O addres range use fast timings.</DESCRIPTION>
	<CONFIGNAME>FAST_TIME_11</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="1">
	<FRAME>IDE Controller tweaks (secondary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>IORDY sampling primary (master)</WIDGETTEXT>
	<DESCRIPTION>0</DESCRIPTION>
	<CONFIGNAME>IORDY_10</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x42" bit="5">
	<FRAME>IDE Controller tweaks (secondary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>IORDY sampling primary (slave)</WIDGETTEXT>
	<DESCRIPTION>0</DESCRIPTION>
	<CONFIGNAME>IORDY_11</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="2">
	<FRAME>IDE Controller tweaks (secondary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Secondary master prefetch/posting</WIDGETTEXT>
	<DESCRIPTION>When enabled, prefetch and posting to the secondary IDE port
is enabled for drive 0</DESCRIPTION>
	<CONFIGNAME>PPE10</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="6">
	<FRAME>IDE Controller tweaks (secondary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Secondary slave prefetch/posting</WIDGETTEXT>
	<DESCRIPTION>When enabled, prefetch and posting to the secondary IDE port
is enabled for drive 1</DESCRIPTION>
	<CONFIGNAME>PPE11</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="3">
	<FRAME>IDE Controller tweaks (secondary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>DMA Timing enable Only (master)</WIDGETTEXT>
	<DESCRIPTION>when DTE0=0 DMA and PIO data transfers use the fast timing mode. When DTE0=1 fast timing mode is enabled for DMA transfers. (suggested value 0)</DESCRIPTION>
	<CONFIGNAME>DMA_TIMING_10</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x42" bit="7">
	<FRAME>IDE Controller tweaks (secondary IDE)</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>DMA Timing enable Only (slave)</WIDGETTEXT>
	<DESCRIPTION>when DTE1=0 DMA and PIO data transfers use the fast timing mode. When DTE0=1 fast timing mode is enabled for DMA transfers. (suggested value 0)</DESCRIPTION>
	<CONFIGNAME>DMA_TIMING_11</CONFIGNAME>
	</REGISTER>

<!--- ************************************** -->
	<REGISTER base="0x48" bit="0">
	<FRAME>UDMA/33 Control</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Primary drive 0 UDMA enable</WIDGETTEXT>
	<DESCRIPTION>Enable Ultra DMA/33 mode</DESCRIPTION>
	<CONFIGNAME>PPE3_1</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x48" bit="1">
	<FRAME>UDMA/33 Control</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Primary drive 1 UDMA enable</WIDGETTEXT>
	<DESCRIPTION>Enable Ultra DMA/33 mode</DESCRIPTION>
	<CONFIGNAME>PPE3_2</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x48" bit="2">
	<FRAME>UDMA/33 Control</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Secondary drive 0 UDMA enable</WIDGETTEXT>
	<DESCRIPTION>Enable Ultra DMA/33 mode</DESCRIPTION>
	<CONFIGNAME>PPE3_3</CONFIGNAME>
	</REGISTER>
	<REGISTER base="0x48" bit="3">
	<FRAME>UDMA/33 Control</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Secondary drive 1 UDMA enable</WIDGETTEXT>
	<DESCRIPTION>Enable Ultra DMA/33 mode</DESCRIPTION>
	<CONFIGNAME>PPE3_4</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/Intel/82443-LX.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x8086" id="0x7180">
	<REGISTER base="0x53" bit="5">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Write post during IO bridge access</WIDGETTEXT>
	<DESCRIPTION>Allows writes to be posted while IO access
occurs</DESCRIPTION>
	<CONFIGNAME>WRITE_POST_IO_BRIDGE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x53" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU to PCI IDE posting</WIDGETTEXT>
	<DESCRIPTION>Allows CPU -> IDE transfers to be posted</DESCRIPTION>
	<CONFIGNAME>CPU_TO_PCI_IDE_POSTING</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast MA Waitstates</WIDGETTEXT>
	<DESCRIPTION>Fast MA Waitstates</DESCRIPTION>
	<CONFIGNAME>FAST_MA_WAITSTATES</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58" bit="5">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>2 CLK SDRAM RAS PRECHARGE</WIDGETTEXT>
	<DESCRIPTION>SDRAM RAS precharge takes 2 clocks when enabled.</DESCRIPTION>
	<CONFIGNAME>SDRAM_2CLK_RAS_PRECHARGE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>2 CLK SDRAM CAS Latency</WIDGETTEXT>
	<DESCRIPTION>SDRAM CAS precharge takes 2 clocks when enabled.</DESCRIPTION>
	<CONFIGNAME>SDRAM_2CLK_CAS_LATENCY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x58" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>2 CLK SDRAM RAS to CAS delay</WIDGETTEXT>
	<DESCRIPTION>RAS to CAS takes 2 clocks when enabled.</DESCRIPTION>
	<CONFIGNAME>SDRAM_RAS_TO_CAS_DELAY</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/VIA/82C686A.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1106" id="0x0305">

<!--

There is a stability problem with the Memory Interleave settings.
Until we find more documentation, they are disabled.
:- Probably tristate (See 82C691.xml) -davej

-->

<!--
	<REGISTER base="0x64">
	<FRAME>Memory Interleave settings</FRAME>
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000001</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Bank 0/1 interleaving 2x</WIDGETTEXT>
	<DESCRIPTION>Enable Memory interleaving. This is known to
improve memory throughput by 20% on some sytems.</DESCRIPTION>
	<CONFIGNAME>BANK1_INTERLEAVE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x65">
	<FRAME>Memory Interleave settings</FRAME>
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000001</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Bank 2/3 interleaving 2x</WIDGETTEXT>
	<DESCRIPTION>Enable Memory interleaving. This is known to
improve memory throughput by 20% on some sytems.</DESCRIPTION>
	<CONFIGNAME>BANK2_INTERLEAVE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x66">
	<FRAME>Memory Interleave settings</FRAME>
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000001</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Bank 4/5 interleaving 2x</WIDGETTEXT>
	<DESCRIPTION>Enable Memory interleaving. This is known to
improve memory throughput by 20% on some sytems.</DESCRIPTION>
	<CONFIGNAME>BANK3_INTERLEAVE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x67">
	<FRAME>Memory Interleave settings</FRAME>
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000001</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Bank 6/7 interleaving 2x</WIDGETTEXT>
	<DESCRIPTION>Enable Memory interleaving. This is known to
improve memory throughput by 20% on some sytems.</DESCRIPTION>
	<CONFIGNAME>BANK4_INTERLEAVE</CONFIGNAME>
	</REGISTER>

-->

	<REGISTER base="0x68" bit="6">
	<FRAME>DRAM settings</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Allow multiple banks active</WIDGETTEXT>
	<DESCRIPTION>This option allows multiple memory banks to be 
active at the same time. Enabled is faster.</DESCRIPTION>
	<CONFIGNAME>DRAM_MULTIBANK</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x71" bit="2">
	<FRAME>PCI Bus behavior</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Fast back-to-back write</WIDGETTEXT>
	<DESCRIPTION></DESCRIPTION>
	<CONFIGNAME>FAST_BACK_2_BACK</CONFIGNAME>
	</REGISTER>


	<REGISTER base="0x71" bit="7">
	<FRAME>PCI Bus behavior</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Dynamic Burst</WIDGETTEXT>
	<DESCRIPTION>This option enables automatic detection of PCI bursts.
This is often the optimal setting.</DESCRIPTION>
	<CONFIGNAME>DYNAMIC_BURST</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x71" bit="3">
	<FRAME>PCI Bus behavior</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI Burst</WIDGETTEXT>
	<DESCRIPTION>This option forces all PCI transaction to be bursts.
This option has no effect if Dynamic Burst is enabled.</DESCRIPTION>
	<CONFIGNAME>FORCE_BURST</CONFIGNAME>
	</REGISTER>


	<REGISTER base="0x70" bit="4">
	<FRAME>PCI Bus behavior</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI DRAM prefetch</WIDGETTEXT>
	<DESCRIPTION>This option enables prefetching DRAM for DMA
transactions. This enhances performance for PCI cards.</DESCRIPTION>
	<CONFIGNAME>PCI_PREFETCH</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x70" bit="7">
	<FRAME>PCI Bus behavior</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU to PCI Write posting</WIDGETTEXT>
	<DESCRIPTION>This option enables write-posting (buffering) for CPU to
PCI device transactions.</DESCRIPTION>
	<CONFIGNAME>PCI_CPU_PCI_POST</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x70" bit="6">
	<FRAME>PCI Bus behavior</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI to DRAM Write posting</WIDGETTEXT>
	<DESCRIPTION>This option enables write-posting (buffering) for PCI to
DRAM transactions.</DESCRIPTION>
	<CONFIGNAME>PCI_PCI_DRAM_POST</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/UMC/8891A.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1060" id="0x0891">

	<REGISTER base="0x50" bit="4">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Level 2 cache write through</WIDGETTEXT>
	<DESCRIPTION>Enabled = write through, disabled=writeback</DESCRIPTION>
	<CONFIGNAME>L2_CACHE_WT</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x51" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU -> PCI posted writes</WIDGETTEXT>
	<DESCRIPTION>Enabled allows CPU->PCI write posting.</DESCRIPTION>
	<CONFIGNAME>CPU_PCI_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

</DEVICE>
