=== codecandiescom/powertweak-0.99.5/xml/pci/pci.dtd
<!ELEMENT DEVICE ANY>
<!ELEMENT REGISTER (FRAME?,COMBO?,GROUP?,(BITMASK,(ONBITS,OFFBITS)?)?,TYPE,LOW?,HIGH?,WIDGETTEXT,(DESCRIPTION,CONFIGNAME)?)>

<!ELEMENT FRAME (#PCDATA)>
<!ELEMENT COMBO (#PCDATA)>
<!ELEMENT GROUP (#PCDATA)>

<!ELEMENT BITMASK (#PCDATA)>
<!ELEMENT ONBITS (#PCDATA)>
<!ELEMENT OFFBITS (#PCDATA)>

<!ELEMENT WIDGETTEXT (#PCDATA)>
<!ELEMENT CONFIGNAME (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT LOW (#PCDATA)>
<!ELEMENT HIGH (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>

<!ATTLIST DEVICE
vendor	CDATA	#REQUIRED
id	CDATA #REQUIRED
>

<!ATTLIST REGISTER
base	CDATA	#REQUIRED
bit	CDATA	#IMPLIED
>

=== codecandiescom/powertweak-0.99.5/xml/pci/VIA/82C686A-2.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1106" id="0x8305">
	<REGISTER base="0x40" bit="4">
	<FRAME>AGP Bus Control</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP to DRAM Prefetch</WIDGETTEXT>
	<DESCRIPTION>Enables AGP cards to prefetch DRAM memory.
This enhances the memorybandwith of such devices, potentially
at the cost of other devices.</DESCRIPTION>
	<CONFIGNAME>AGP_PREFETCH</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="6">
	<FRAME>AGP Bus Control</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP Dynamic Burst</WIDGETTEXT>
	<DESCRIPTION>This option enables Dynamic Burst detection for
AGP Cards. Recommended.</DESCRIPTION>
	<CONFIGNAME>AGP_DYNAMIC_BURST</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="7">
	<FRAME>AGP Bus Control</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU to AGP posted writes</WIDGETTEXT>
	<DESCRIPTION>Enables the buffering of CPU to AGP writes</DESCRIPTION>
	<CONFIGNAME>AGP_POST_WRITE</CONFIGNAME>
	</REGISTER>


</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/VIA/82C597-1.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1106" id="0x8597">

	<REGISTER base="0x40" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU to AGP posted writes</WIDGETTEXT>
	<DESCRIPTION>Enables write posting on CPU->AGP transfers</DESCRIPTION>
	<CONFIGNAME>CPU_TO_AGP_POSTED_WRITES</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU to AGP dynamic burst</WIDGETTEXT>
	<DESCRIPTION>Enables dynamic bursting on CPU->AGP transfers</DESCRIPTION>
	<CONFIGNAME>CPU_TO_AGP_DYNAMIC_BURST</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x40" bit="5">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU to AGP 1 waitstate burst write</WIDGETTEXT>
	<DESCRIPTION>Enables single waitstate burst writes</DESCRIPTION>
	<CONFIGNAME>CPU_TO_AGP_1WS_BURST_WR</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x41" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU backoff on AGP read retry</WIDGETTEXT>
	<DESCRIPTION>Tells the CPU to wait while the AGP bus retries a read</DESCRIPTION>
	<CONFIGNAME>CPU_BACKOFF_ON_AGP_RD_RETRY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Read prefetch for enhance command</WIDGETTEXT>
	<DESCRIPTION>When enabled, prefetches only when an enhance command occurs.
When disabled, prefetching always occurs.</DESCRIPTION>
	<CONFIGNAME>RD_PREFETCH_FOR_ENHANCE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="6">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP 1 waitstate write</WIDGETTEXT>
	<DESCRIPTION>Enables single waitstate writes to the AGP bus</DESCRIPTION>
	<CONFIGNAME>AGP_1WS_WR</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x42" bit="5">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>AGP 1 waitstate read</WIDGETTEXT>
	<DESCRIPTION>Enables single waitstate reads from the AGP bus</DESCRIPTION>
	<CONFIGNAME>AGP_1WS_RD</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/VIA/82C686.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1106" id="0x0686">
	<REGISTER base="0x64">
	<FRAME>Documentation notice</FRAME>
	<BITMASK>00000000</BITMASK>
	<ONBITS> 00000000</ONBITS>
	<OFFBITS>00000000</OFFBITS>
	<TYPE>Label</TYPE>
	<WIDGETTEXT>
 The authors of Powertweak would like to thank VIA Technologies, Inc.
 for NOT providing documentation on tweaking your chipset.
</WIDGETTEXT>
	<DESCRIPTION></DESCRIPTION>
	<CONFIGNAME>FTSO_VIA</CONFIGNAME>
	</REGISTER>


</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/Intel/82443-BX-NOAGP.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x8086" id="0x7192">
	<REGISTER base="0x52" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Host bus fast ready</WIDGETTEXT>
	<DESCRIPTION>Assertion of DRAM data occurs on the same
clock the snoop result is sampled when enabled.
When disabled, an extra clock cycle is needed.</DESCRIPTION>
	<CONFIGNAME>HOST_FAST_DATA_READY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x50" bit="3">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>USWC Write post during IO bridge access</WIDGETTEXT>
	<DESCRIPTION>Enabling this allows host USWC writes to PCI
memory to be posted</DESCRIPTION>
	<CONFIGNAME>USWC_WRITE_POST_IO_ACCESS</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x50" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Maximum in-order queue depth</WIDGETTEXT>
	<DESCRIPTION>Sets the in-order queue depth to the maximum</DESCRIPTION>
	<CONFIGNAME>IN_ORDER_QUEUE_DEPTH</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x7a" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Power down SDRAM when idle</WIDGETTEXT>
	<DESCRIPTION>When enabled, an SDRAM row in idle state will be
issued a power down command. The SDRAM row will exit power down mode
only when there is a request to access this particular row.</DESCRIPTION>
	<CONFIGNAME>POWER_DOWN_SDRAM</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/Intel/82424.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x8086" id="0x0483">

	<REGISTER base="0x53" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU->PCI posted write</WIDGETTEXT>
	<DESCRIPTION>Enables CPU->PCI write posting</DESCRIPTION>
	<CONFIGNAME>CPU_PCI_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x53" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>CPU->RAM posted write</WIDGETTEXT>
	<DESCRIPTION>Enables CPU->RAM write posting</DESCRIPTION>
	<CONFIGNAME>CPU_RAM_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x54" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI->RAM posted write</WIDGETTEXT>
	<DESCRIPTION>Enables PCI->RAM write posting</DESCRIPTION>
	<CONFIGNAME>PCI_RAM_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x54" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI Burst</WIDGETTEXT>
	<DESCRIPTION>Enables PCI Bursting</DESCRIPTION>
	<CONFIGNAME>PCI_BURST</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/ALI/M5243.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x10b9" id="0x5243">

	<REGISTER base="0x89">
	<FRAME>PCI bus</FRAME>
	<TYPE>Slider</TYPE>
	<LOW>0</LOW>
	<HIGH>255</HIGH>
	<WIDGETTEXT>Minimum PCI66 slice on PCI66 bus</WIDGETTEXT>
	<DESCRIPTION>This number controls the minimum number of
PCI66 bus cycles a device gets. If the device wants the bus longer, 
it might be interrupted. Setting this to a higher value increases
throughput but decreases latency. 
</DESCRIPTION>
	<CONFIGNAME>PCI_SLICE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x8A">
	<FRAME>PCI bus</FRAME>
	<TYPE>Slider</TYPE>
	<LOW>0</LOW>
	<HIGH>255</HIGH>
	<WIDGETTEXT>Minimum CPU slice on PCI66 bus</WIDGETTEXT>
	<DESCRIPTION>This number controls the minimum number of
PCI66 bus cycles the CPU gets. If the CPU  wants the bus longer, 
it might be interrupted. Setting this to a higher value increases
throughput but decreases latency. 
</DESCRIPTION>
	<CONFIGNAME>CPU_SLICE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x8F">
	<FRAME>PCI bus</FRAME>
	<TYPE>Slider</TYPE>
	<LOW>0</LOW>
	<HIGH>255</HIGH>
	<WIDGETTEXT>Minimum PCI33 slice on PCI66 bus</WIDGETTEXT>
	<DESCRIPTION>This number controls the minimum number of
PCI bus cycles the PCI33 bus gets on the PCI66. 
Setting this to a higher value increases throughput but decreases latency. 
</DESCRIPTION>
	<CONFIGNAME>CPU_SLICE</CONFIGNAME>
	</REGISTER>


</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/Intel/82371AB-PIIX4-0.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x8086" id="0x7110">

	<REGISTER base="0x4c" bit="6">
	<FRAME>I/O Recovery times.</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>8 bit I/O recovery</WIDGETTEXT>
	<DESCRIPTION>Enable this to use the recovery time defined
in the slider below. Disable to use standard 3.5 SYSCLK recovery
timing</DESCRIPTION>
	<CONFIGNAME>8BIT_IO_RECOVERY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x4c">
	<FRAME>I/O Recovery times.</FRAME>
	<BITMASK>00111000</BITMASK>
	<ONBITS> 00111000</ONBITS>
	<OFFBITS>00111000</OFFBITS>
	<TYPE>Slider</TYPE>
	<LOW>8</LOW>
	<HIGH>56</HIGH>
	<WIDGETTEXT>8 bit I/O recovery time</WIDGETTEXT>
	<DESCRIPTION>When "8 bit I/O recovery" is enabled, this
tweak defines the number of SYSCLKs added to the standard 3.5
SYSCLK recovery time for 8 bit I/O
	</DESCRIPTION>
	<CONFIGNAME>8BIT_IO_RECOVERY_TIME</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x4c" bit="2">
	<FRAME>I/O Recovery times.</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>16 bit I/O recovery</WIDGETTEXT>
	<DESCRIPTION>Enable this to use the recovery time defined
in the slider below. Disable to use standard 3.5 SYSCLK recovery
timing</DESCRIPTION>
	<CONFIGNAME>16BIT_IO_RECOVERY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x4c">
	<FRAME>I/O Recovery times.</FRAME>
	<BITMASK>00000011</BITMASK>
	<ONBITS> 00000011</ONBITS>
	<OFFBITS>00000011</OFFBITS>
	<TYPE>Slider</TYPE>
	<LOW>1</LOW>
	<HIGH>3</HIGH>
	<WIDGETTEXT>16 bit I/O recovery time</WIDGETTEXT>
	<DESCRIPTION>When "16 bit I/O recovery" is enabled, this
tweak defines the number of SYSCLKs added to the standard 3.5
SYSCLK recovery time for 16 bit I/O
	</DESCRIPTION>
	<CONFIGNAME>16BIT_IO_RECOVERY_TIME</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x6b" bit="7">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Host to PCI bridge retry</WIDGETTEXT>
	<DESCRIPTION>This tweak when enabled causes PIIX4 to retry
without initiating a delayed transaction, CPU initiated non LOCK#,
PCI cycles. No delayed transactions to PIIX4 may currently be pending
and passive release must be active. When disabled, PIIX4 accepts these
cycles as normal which may include retry with initiation of a
delayed transaction.</DESCRIPTION>
	<CONFIGNAME>HOST_TO_PCI_RETRY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x82" bit="2">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>USB Passive release</WIDGETTEXT>
	<DESCRIPTION>When enabled, this allows PIIX4 to use passive
release while transferring control information or data for USB
transactions. When disabled, PIIX4 will perform PCI accesses for
USB without using passive release.</DESCRIPTION>
	<CONFIGNAME>USB_PASSIVE_RELEASE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x82" bit="1">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Passive release</WIDGETTEXT>
	<DESCRIPTION>Enables the passive release mechanism when PIIX4
is a PCI master.</DESCRIPTION>
	<CONFIGNAME>PASSIVE_RELEASE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x82" bit="0">
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Delayed transaction.</WIDGETTEXT>
	<DESCRIPTION>Enables the delayed transaction mechanism when PIIX4
is the target of a PCI transaction</DESCRIPTION>
	<CONFIGNAME>DELAYED_TRANSACTION</CONFIGNAME>
	</REGISTER>

</DEVICE>

=== codecandiescom/powertweak-0.99.5/xml/pci/Cypress/CY82C693U.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE DEVICE SYSTEM "../pci.dtd">
<DEVICE vendor="0x1080" id="0xC693">
	<REGISTER base="0x44" bit="4">
	<FRAME>PCI->ISA</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>Retry on excessive delay</WIDGETTEXT>
	<DESCRIPTION>Retries if delay will be longer than 16 PCI clock cycles.
</DESCRIPTION>
	<CONFIGNAME>RETRY_ON_EXCESSIVE_DELAY</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x44" bit="2">
	<FRAME>PCI->ISA</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>PCI posted write</WIDGETTEXT>
	<DESCRIPTION>Enables PCI posted write buffers.
</DESCRIPTION>
	<CONFIGNAME>PCI_POSTED_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x44" bit="1">
	<FRAME>PCI->ISA</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>ISA Master line buffer</WIDGETTEXT>
	<DESCRIPTION>When disabled, ISA master transfers will cause PCI
single (8/16bit) transfers. When enabled, these transfers will cause
PCI 8-byte transfers (pre-read 8 bytes).
</DESCRIPTION>
	<CONFIGNAME>ISA_MASTER_LINE_BUFFER</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x44" bit="0">
	<FRAME>PCI->ISA</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>DMA line buffer</WIDGETTEXT>
	<DESCRIPTION>When disabled, DMA transfers will cause PCI single
(8/16bit) transfers. When enabled, these transfers will cause PCI
8-byte transfers (pre-read 8 bytes).
</DESCRIPTION>
	<CONFIGNAME>DMA_LINE_BUFFER</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x45" bit="1">
	<FRAME>PCI->ISA</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>ISA Master post-write</WIDGETTEXT>
	<DESCRIPTION>Enables ISA post write buffers.
</DESCRIPTION>
	<CONFIGNAME>ISA_MASTER_POST_WRITE</CONFIGNAME>
	</REGISTER>

	<REGISTER base="0x45" bit="0">
	<FRAME>PCI->ISA</FRAME>
	<TYPE>Checkbox</TYPE>
	<WIDGETTEXT>DMA post-write</WIDGETTEXT>
	<DESCRIPTION>Enables DMA post write buffers.
</DESCRIPTION>
	<CONFIGNAME>DMA_POST_WRITE</CONFIGNAME>
	</REGISTER>

</DEVICE>
