=== codecandiescom/powertweak-0.99.5/xml/cpu/x86/x86.dtd
<!ELEMENT MSRENTRY ANY>
<!ELEMENT MSR (STEPPING?,FRAME?,COMBO?,GROUP?,WIDGETTEXT,(BITMASK,(ONBITS,OFFBITS)?)?,CONFIGNAME,TYPE,(LOW,HIGH)?,DESCRIPTION?)>
<!ELEMENT STEPPING (#PCDATA)>
<!ELEMENT FRAME (#PCDATA)>
<!ELEMENT COMBO (#PCDATA)>
<!ELEMENT GROUP (#PCDATA)>

<!ELEMENT BITMASK (#PCDATA)>
<!ELEMENT ONBITS (#PCDATA)>
<!ELEMENT OFFBITS (#PCDATA)>

<!ELEMENT WIDGETTEXT (#PCDATA)>
<!ELEMENT CONFIGNAME (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT LOW (#PCDATA)>
<!ELEMENT HIGH (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>

<!ATTLIST MSRENTRY
vendor	CDATA	#REQUIRED
family	CDATA	#REQUIRED
model	CDATA	#REQUIRED
modeloper CDATA #IMPLIED
>

<!ATTLIST MSR
register	CDATA	#REQUIRED
bit	CDATA	#IMPLIED
>

<!ATTLIST STEPPING
operator	CDATA	#IMPLIED
>

=== codecandiescom/powertweak-0.99.5/xml/cpu/x86/PentiumIV.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE MSRENTRY SYSTEM "x86.dtd">

<!-- MSR's on the Intel Pentium IV -->

<MSRENTRY>
	<MSR register="0x0000002A" bit="26">
	    <WIDGETTEXT>Low power mode</WIDGETTEXT>
	    <CONFIGNAME>PIV_LOW_POWER_MODE</CONFIGNAME>
	    <TYPE>Checkbox</TYPE>
	    <DESCRIPTION>When set, low power mode is enabled.</DESCRIPTION>
	</MSR>

	<MSR register="0x000001A0" bit="0">
	    <WIDGETTEXT>Fast strings enable</WIDGETTEXT>
	    <CONFIGNAME>PIV_ENABLE_FAST_STRINGS</CONFIGNAME>
	    <TYPE>Checkbox</TYPE>
	    <DESCRIPTION>When set, the fast-string operations
of the Pentium IV are enabled.</DESCRIPTION>
	</MSR>

	<MSR register="0x000001A0" bit="2">
	    <WIDGETTEXT>Fast strings enable</WIDGETTEXT>
	    <CONFIGNAME>PIV_FOPCODE_COMPATABILITY</CONFIGNAME>
	    <TYPE>Checkbox</TYPE>
	    <DESCRIPTION>When set, fopcode compatability mode is enabled.
</DESCRIPTION>
	</MSR>

	<MSR register="0x000001A0" bit="4">
	    <WIDGETTEXT>Split Lock Disable</WIDGETTEXT>
	    <CONFIGNAME>PIV_SPLIT_LOCK</CONFIGNAME>
	    <TYPE>Checkbox</TYPE>
	    <DESCRIPTION>When set, the split-lock feature of the Pentium IV
is disabled.</DESCRIPTION>
	</MSR>
</MSRENTRY>

=== codecandiescom/powertweak-0.99.5/xml/cpu/x86/AMD-K6-3+.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE MSRENTRY SYSTEM "x86.dtd">

<!-- MSR's on the AMD K6-3 -->

<MSRENTRY>
	<MSR register="0xC0000080" bit="1">
		<WIDGETTEXT>Data prefetch enable</WIDGETTEXT>
		<CONFIGNAME>MSR_AMD_K6_3_DPE</CONFIGNAME>
		<TYPE>Checkbox</TYPE>
		<DESCRIPTION>Setting this enables data prefetching.
Cache misses initiated by a memory read within a 32 byte
cacheline are conditionally followed by cacheline fetches
of the other line in the 64 byte sector</DESCRIPTION>
	</MSR>

	<MSR register="0xC0000080">
		<FRAME>EWBE</FRAME>
		<GROUP>EWBE</GROUP>
		<WIDGETTEXT>Best</WIDGETTEXT>
		<BITMASK>00000000 00000000 00000000 00001100</BITMASK>
		<ONBITS> 00000000 00000000 00000000 00001100</ONBITS>
		<OFFBITS>00000000 00000000 00000000 00000000</OFFBITS>
		<CONFIGNAME>MSR_AMD_K6_3_EWBE_11</CONFIGNAME>
		<TYPE>RadioButton</TYPE>
		<DESCRIPTION>Global EWBE disable.
When enabled, the processor does not attempt to enforce any
write ordering internally or externally.
This is the maximum performance setting.</DESCRIPTION>
	</MSR>

	<MSR register="0xC0000080">
		<FRAME>EWBE</FRAME>
		<GROUP>EWBE</GROUP>
		<WIDGETTEXT>Close-to-best</WIDGETTEXT>
		<BITMASK>00000000 00000000 00000000 00001100</BITMASK>
		<ONBITS> 00000000 00000000 00000000 00000100</ONBITS>
		<OFFBITS>00000000 00000000 00000000 00000000</OFFBITS>
		<CONFIGNAME>MSR_AMD_K6_3_EWBE_01</CONFIGNAME>
		<TYPE>RadioButton</TYPE>
		<DESCRIPTION>Speculative EWBE disable.
When enabled, the processor enforces strong ordering for all
internal write cycles with the exception of write cycles
addresed to a range of memory defined as uncacheable or
write-combining by the MTRRs.
This is the medium performance setting.</DESCRIPTION>
	</MSR>

	<MSR register="0xC0000080">
		<FRAME>EWBE</FRAME>
		<GROUP>EWBE</GROUP>
		<WIDGETTEXT>Slowest</WIDGETTEXT>
		<BITMASK>00000000 00000000 00000000 00001100</BITMASK>
		<ONBITS> 00000000 00000000 00000000 00000000</ONBITS>
		<OFFBITS>00000000 00000000 00000000 00000000</OFFBITS>
		<CONFIGNAME>MSR_AMD_K6_3_EWBE_00</CONFIGNAME>
		<TYPE>RadioButton</TYPE>
		<DESCRIPTION>Strong ordering for all internal and external
write cycles. In this setting the processor assumes that strong
order must be maintained between writes to the merge buffer and
writes that hit the processors cache.
This is the lowest performance setting.</DESCRIPTION>
	</MSR>

<!-- We have reports of this tweak rebooting the machine, so disabled 
     for now -->
<!--

	<MSR register="0xC0000080" bit="4">
		<WIDGETTEXT>L2 Disable</WIDGETTEXT>
		<CONFIGNAME>MSR_AMD_K6_3_L2D</CONFIGNAME>
		<TYPE>Checkbox</TYPE>
		<DESCRIPTION>If this is 'on', your L2 cache is off.
Disable this for best performance</DESCRIPTION>
	</MSR>
-->
</MSRENTRY>

=== codecandiescom/powertweak-0.99.5/xml/cpu/x86/Pentium-MMX.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE MSRENTRY SYSTEM "x86.dtd">

<!-- MSR's on the Intel Pentium MMX -->

<MSRENTRY>
	<MSR register="0x0000000E" bit="21">
		<WIDGETTEXT>Low powermode enable</WIDGETTEXT>
		<CONFIGNAME>PMMX_LOWPOWER</CONFIGNAME>
		<TYPE>Checkbox</TYPE>
		<DESCRIPTION>Setting this enables the low powermode of
Pentium MMX processors. This is very useful for laptops.</DESCRIPTION>
	</MSR>

	<MSR register="0x0000000E">
	    <WIDGETTEXT>Auto halt feature enable</WIDGETTEXT>
	    <BITMASK>00000000 00000000 00000000 01000000</BITMASK>
	    <ONBITS> 00000000 00000000 00000000 00000000</ONBITS>
	    <OFFBITS>00000000 00000000 00000000 01000000</OFFBITS>
	    <CONFIGNAME>PMMX_DISABLE_AUTOHLT</CONFIGNAME>
	    <TYPE>Checkbox</TYPE>
	    <DESCRIPTION>Setting this will enable the auto-halt feature,
this is useful for powersaving on laptops.</DESCRIPTION>
	</MSR>

</MSRENTRY>

=== codecandiescom/powertweak-0.99.5/xml/cpu/x86/PentiumIII.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE MSRENTRY SYSTEM "x86.dtd">

<MSRENTRY>

	<MSR register="0x0000002A" bit="26">
	    <WIDGETTEXT>Low power mode</WIDGETTEXT>
	    <CONFIGNAME>P6_LOW_POWER_MODE</CONFIGNAME>
	    <TYPE>Checkbox</TYPE>
	    <DESCRIPTION>When set, low power mode is enabled.</DESCRIPTION>
	</MSR>

	<MSR register="0x00000033" bit="30">
	    <WIDGETTEXT>Streaming buffer disable</WIDGETTEXT>
	    <CONFIGNAME>P6_STREAMING_BUFFER_DISABLE</CONFIGNAME>
	    <TYPE>Checkbox</TYPE>
	    <DESCRIPTION>When set, the streaming buffer is disabled.</DESCRIPTION>
	</MSR>

</MSRENTRY>

=== codecandiescom/powertweak-0.99.5/xml/cpu/x86/AMD-K5.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE MSRENTRY SYSTEM "x86.dtd">

<!-- MSR's on the AMD K5 -->

<MSRENTRY>
	<MSR register="0x00000083" bit="7">
		<WIDGETTEXT>Disable data cache</WIDGETTEXT>
		<CONFIGNAME>MSR_AMD_K5_DISABLE_DCACHE</CONFIGNAME>
		<TYPE>Checkbox</TYPE>
		<DESCRIPTION>Setting this will switch off the data cache.
This setting should be disabled for best performance.</DESCRIPTION>
	</MSR>

	<MSR register="0x00000083" bit="6">
		<WIDGETTEXT>Disable instruction cache</WIDGETTEXT>
		<CONFIGNAME>MSR_AMD_K5_DISABLE_ICACHE</CONFIGNAME>
		<TYPE>Checkbox</TYPE>
		<DESCRIPTION>Setting this will switch off the instruction cache.
This setting should be disabled for best performance.</DESCRIPTION>
	</MSR>

	<MSR register="0x00000083" bit="5">
		<WIDGETTEXT>Disable branch prediction</WIDGETTEXT>
		<CONFIGNAME>MSR_AMD_K5_DISABLE_ICACHE</CONFIGNAME>
		<TYPE>Checkbox</TYPE>
		<DESCRIPTION>Setting this will switch off the CPU branch
prediction feature. This setting should be disabled for best performance.</DESCRIPTION>
	</MSR>

	<MSR register="0x00000083" bit="0">
		<WIDGETTEXT>Disable Stopping CPU clock in HLT state</WIDGETTEXT>
		<CONFIGNAME>MSR_AMD_K5_DISABLE_ICACHE</CONFIGNAME>
		<TYPE>Checkbox</TYPE>
		<DESCRIPTION>Whilst idle the CPU can halt the clock.
This setting should be disabled for best performance.</DESCRIPTION>
	</MSR>

</MSRENTRY>
