=== codecandiescom/powertweak-0.99.5/xml/proc/proc.dtd
<!ELEMENT PROCENTRIES ANY>
<!ELEMENT PROCENTRY (MENU,SUBMENU,SUBSUBMENU?,TAB,FRAME?,GROUP?,WIDGETTEXT,CONFIGNAME,TYPE,(LOW,HIGH)?,ELEMENT,FILE,DESCRIPTION?)>
<!ELEMENT MENU (#PCDATA)>
<!ELEMENT SUBMENU (#PCDATA)>
<!ELEMENT SUBSUBMENU (#PCDATA)>
<!ELEMENT TAB (#PCDATA)>
<!ELEMENT FRAME (#PCDATA)>
<!ELEMENT GROUP (#PCDATA)>
<!ELEMENT WIDGETTEXT (#PCDATA)>
<!ELEMENT CONFIGNAME (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT LOW (#PCDATA)>
<!ELEMENT HIGH (#PCDATA)>
<!ELEMENT FILE (#PCDATA)>
<!ELEMENT ELEMENT (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>

=== codecandiescom/powertweak-0.99.5/xml/proc/raid.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROCENTRIES SYSTEM "proc.dtd">

<PROCENTRIES>

<!-- Hardware / RAID -->

	<PROCENTRY>
	<MENU>Hardware</MENU>
	<SUBMENU>Disk</SUBMENU>
	<SUBSUBMENU>RAID</SUBSUBMENU>
	<TAB>RAID</TAB>
	<WIDGETTEXT>Min speed limit</WIDGETTEXT>
	<CONFIGNAME>dev/raid/speed_limit_min</CONFIGNAME>
	<TYPE>Slider</TYPE>
	<LOW>100</LOW>
	<HIGH>1000</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/dev/raid/speed_limit_min</FILE>
	<DESCRIPTION>Minimum level throughput.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Hardware</MENU>
	<SUBMENU>Disk</SUBMENU>
	<SUBSUBMENU>RAID</SUBSUBMENU>
	<TAB>RAID</TAB>
	<WIDGETTEXT>Max speed limit</WIDGETTEXT>
	<CONFIGNAME>dev/raid/speed_limit_max</CONFIGNAME>
	<TYPE>Slider</TYPE>
	<LOW>100000</LOW>
	<HIGH>200000</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/dev/raid/speed_limit_max</FILE>
	<DESCRIPTION>Maximum level throughput.</DESCRIPTION>
	</PROCENTRY>

</PROCENTRIES>
