=== codecandiescom/powertweak-0.99.5/xml/proc/proc.dtd
<!ELEMENT PROCENTRIES ANY>
<!ELEMENT PROCENTRY (MENU,SUBMENU,SUBSUBMENU?,TAB,FRAME?,GROUP?,WIDGETTEXT,CONFIGNAME,TYPE,(LOW,HIGH)?,ELEMENT,FILE,DESCRIPTION?)>
<!ELEMENT MENU (#PCDATA)>
<!ELEMENT SUBMENU (#PCDATA)>
<!ELEMENT SUBSUBMENU (#PCDATA)>
<!ELEMENT TAB (#PCDATA)>
<!ELEMENT FRAME (#PCDATA)>
<!ELEMENT GROUP (#PCDATA)>
<!ELEMENT WIDGETTEXT (#PCDATA)>
<!ELEMENT CONFIGNAME (#PCDATA)>
<!ELEMENT TYPE (#PCDATA)>
<!ELEMENT LOW (#PCDATA)>
<!ELEMENT HIGH (#PCDATA)>
<!ELEMENT FILE (#PCDATA)>
<!ELEMENT ELEMENT (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>

=== codecandiescom/powertweak-0.99.5/xml/proc/cdrom.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROCENTRIES SYSTEM "proc.dtd">

<PROCENTRIES>

<!-- Hardware / CDROM -->
	<PROCENTRY>
	<MENU>Hardware</MENU>
	<SUBMENU>CDROM</SUBMENU>
	<TAB>CDROM settings</TAB>
	<WIDGETTEXT>Close door on mount</WIDGETTEXT>
	<CONFIGNAME>dev/cdrom/autoclose</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/dev/cdrom/autoclose</FILE>
	<DESCRIPTION>
Setting this option will cause the kernel to close the
door of the CDROM-drive when a mount of the CDROM is 
attempted. This is generally a good idea, unless you 
use autofs to automatically mount the drive.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Hardware</MENU>
	<SUBMENU>CDROM</SUBMENU>
	<TAB>CDROM settings</TAB>
	<WIDGETTEXT>Eject the CDROM on unmount</WIDGETTEXT>
	<CONFIGNAME>dev/cdrom/autoeject</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/dev/cdrom/autoeject</FILE>
	<DESCRIPTION>
Setting this option will cause the kernel to open
door of the CDROM drive when the CDROM is unmounted.
A lot of people like this, but it can also be an 
annoyance, hence it is disabled by default.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Hardware</MENU>
	<SUBMENU>CDROM</SUBMENU>
	<TAB>CDROM settings</TAB>
	<WIDGETTEXT>Check for media-type</WIDGETTEXT>
	<CONFIGNAME>dev/cdrom/check_media</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/dev/cdrom/check_media</FILE>
	<DESCRIPTION>
Setting this option will cause the kernel to check the type
of the CD (data, audio, VCD) before using it.
In principle, this is a good thing. However, some CDROM drives
have "issues" with this, hence the option defaults to off.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Hardware</MENU>
	<SUBMENU>CDROM</SUBMENU>
	<TAB>CDROM settings</TAB>
	<WIDGETTEXT>Lock the tray on use</WIDGETTEXT>
	<CONFIGNAME>dev/cdrom/lock</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/dev/cdrom/lock</FILE>
	<DESCRIPTION>
Setting this option will cause the kernel to lock
the tray when the cdrom is mounted. This is the safe 
behavior. There might be reasons not to want this though.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Hardware</MENU>
	<SUBMENU>CDROM</SUBMENU>
	<TAB>CDROM settings</TAB>
	<WIDGETTEXT>Enable debugging</WIDGETTEXT>
	<CONFIGNAME>dev/cdrom/debug</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/dev/cdrom/debug</FILE>
	<DESCRIPTION>
Setting this option will enable debug-messages.
Use this only when you have problems and want to
help the maintainers fix those.</DESCRIPTION>
	</PROCENTRY>
</PROCENTRIES>

=== codecandiescom/powertweak-0.99.5/xml/proc/tuxwebserv.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROCENTRIES SYSTEM "proc.dtd">

<PROCENTRIES>

<!-- Tux -->
	<PROCENTRY>
	<MENU>Applications</MENU>
	<SUBMENU>Tux</SUBMENU>
	<TAB>Tux settings</TAB>
	<WIDGETTEXT>Logging</WIDGETTEXT>
	<CONFIGNAME>net/tux/logging</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/net/http/logging</FILE>
	<DESCRIPTION>Determines whether Tux logs requests.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Applications</MENU>
	<SUBMENU>Tux</SUBMENU>
	<TAB>Tux settings</TAB>
	<WIDGETTEXT>Nonagle</WIDGETTEXT>
	<CONFIGNAME>net/tux/nonagle</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/net/tux/nonagle</FILE>
	<DESCRIPTION>Sets whether the NAGLE algorithm should be used
When disabled, sockets are in TCP_CORK mode, enabling sets them
to TCP_NODELAY.</DESCRIPTION>
	</PROCENTRY>

</PROCENTRIES>

=== codecandiescom/powertweak-0.99.5/xml/proc/netdev.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROCENTRIES SYSTEM "proc.dtd">
<PROCENTRIES>

<!-- Network -->
	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>TCP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>Send Redirects</WIDGETTEXT>
	<CONFIGNAME>NET_TCPIP_DEV_SEND_REDIRECTS</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/conf/*/send_redirects</FILE>
	<DESCRIPTION>Send redirects, if router.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>TCP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>Secure Redirects</WIDGETTEXT>
	<CONFIGNAME>NET_TCPIP_DEV_SECURE_REDIRECTS</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/conf/*/secure_redirects</FILE>
	<DESCRIPTION>Accept ICMP redirect messages only for gateways
listed in default gateway list.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>TCP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>Accept Redirects</WIDGETTEXT>
	<CONFIGNAME>NET_TCPIP_DEV_ACCEPT_REDIRECTS</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/conf/*/accept_redirects</FILE>
	<DESCRIPTION>Accept ICMP redirect messages, enable for hosts,
disable for routers.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>TCP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>Proxy Arp</WIDGETTEXT>
	<CONFIGNAME>NET_TCPIP_DEV_PROXYARP</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/conf/*/proxy_arp</FILE>
	<DESCRIPTION>Enable proxying of ARP requests.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>TCP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>Log martians</WIDGETTEXT>
	<CONFIGNAME>NET_TCPIP_DEV_LOG_MARTIANS</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/conf/*/log_martians</FILE>
	<DESCRIPTION>Log packets with impossible addresses to kernel log.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>TCP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>Forwarding</WIDGETTEXT>
	<CONFIGNAME>NET_TCPIP_DEV_FORWARDING</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/conf/*/forwarding</FILE>
	<DESCRIPTION>Enable forwarding of IP packets on this interface.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>TCP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>shared_media</WIDGETTEXT>
	<CONFIGNAME>NET_TCPIP_DEV_SHARED_MEDIA</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/conf/*/shared_media</FILE>
	<DESCRIPTION>Send(router) or accept(host) RFC1620 shared media
redirects. Overrides Secure redirects.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>TCP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>Accept source route</WIDGETTEXT>
	<CONFIGNAME>NET_TCPIP_DEV_ACCEPT_SOURCE_ROUTE</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/conf/*/accept_source_route</FILE>
	<DESCRIPTION>Accept packets with SRR option. Enable for routers,
Disable for others.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>TCP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>RP Filter</WIDGETTEXT>
	<CONFIGNAME>NET_TCPIP_DEV_ACCEPT_RP_FILTER</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/conf/*/rp_filter</FILE>
	<DESCRIPTION>Do source validation by reversed path, as specified
in RFC1812. Enabled is recommended for single homed hosts and stub
network routers. Could cause problems for complicated (not loop free)
networks running a slow unreliable protocol (sort of RIP) or using
static routes.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>ARP</SUBMENU>
	<TAB>*</TAB>
	<WIDGETTEXT>ARP cache lifetime (seconds)</WIDGETTEXT>
	<CONFIGNAME>net/ipv4/neigh/gc_stale_time</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>10</LOW>
	<HIGH>360</HIGH>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/neigh/*/gc_stale_time</FILE>
	<DESCRIPTION>Time (in second) that cached IP:MAC pairs are 
kept in the ARP cache before they are considered "stale".</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>ARP</SUBMENU>
	<TAB>*</TAB>
	<FRAME>ARP cache size</FRAME>
	<WIDGETTEXT>Minimum number of entries</WIDGETTEXT>
	<CONFIGNAME>net/ipv4/neigh/gc_thresh1</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>16</LOW>
	<HIGH>512</HIGH>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/neigh/*/gc_thresh1</FILE>
	<DESCRIPTION>Minimum number of entries to keep in the ARP cache.
If the number of entries in the ARP cache is smaller than this
number, the garbage collector is not run.</DESCRIPTION>
	</PROCENTRY>


	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>ARP</SUBMENU>
	<TAB>*</TAB>
	<FRAME>ARP cache size</FRAME>
	<WIDGETTEXT>Soft maximum number of entries</WIDGETTEXT>
	<CONFIGNAME>net/ipv4/neigh/gc_thresh2</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>16</LOW>
	<HIGH>1024</HIGH>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/neigh/*/gc_thresh2</FILE>
	<DESCRIPTION>(soft) maximum number of entries to keep in the ARP
cache. This maximum is a soft limit and can be temporarily exceed for 
a duration of 5 seconds.</DESCRIPTION>
	</PROCENTRY>


	<PROCENTRY>
	<MENU>Networking</MENU>
	<SUBMENU>ARP</SUBMENU>
	<TAB>*</TAB>
	<FRAME>ARP cache size</FRAME>
	<WIDGETTEXT>Hard maximum number of entries</WIDGETTEXT>
	<CONFIGNAME>net/ipv4/neigh/gc_thresh3</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>16</LOW>
	<HIGH>2048</HIGH>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/net/ipv4/neigh/*/gc_thresh3</FILE>
	<DESCRIPTION>(hard) maximum number of entries to keep in the ARP
cache. If this number is exceeded, the garbage-collector is 
run immediatly.</DESCRIPTION>
	</PROCENTRY>

</PROCENTRIES>

=== codecandiescom/powertweak-0.99.5/xml/proc/kernel.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROCENTRIES SYSTEM "proc.dtd">
<PROCENTRIES>

<!-- Kernel -->
	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Security</SUBMENU>
	<TAB>Security</TAB>
	<WIDGETTEXT>immediate reboot on ctrl-alt-del</WIDGETTEXT>
	<CONFIGNAME>kernel/ctrl-alt-del</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/kernel/ctrl-alt-del</FILE>
	<DESCRIPTION>When this is unchecked, ctrl-alt-del is trapped and sent to the
init(1) program to handle a graceful restart. However, when this
is checked, Linux's reaction to this key combination will be an
immediate reboot, without syncing its dirty buffers.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Security</SUBMENU>
	<TAB>Security</TAB>
	<WIDGETTEXT>Enable 'magic sysrq'</WIDGETTEXT>
	<CONFIGNAME>kernel/sysrq</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/kernel/sysrq</FILE>
	<DESCRIPTION>In most environments it is not be desirable to allow end users
to use the console debugging sequences. This option enables the
magic key sequences which may be useful when doing kernel
development or debugging a system problem.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Logging</SUBMENU>
	<TAB>Logging</TAB>
	<WIDGETTEXT>Reboot time after a panic</WIDGETTEXT>
	<CONFIGNAME>kernel/panic</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>0</LOW>
	<HIGH>3600</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/kernel/panic</FILE>
	<DESCRIPTION>After a kernel panic the kernel will wait this long before
attempting to reboot the system. Normally this is set to zero to
disable the feature, but for a remote machine you may wish to 
set this.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Logging</SUBMENU>
	<TAB>Logging</TAB>
	<WIDGETTEXT>Space to resume accounting</WIDGETTEXT>
	<CONFIGNAME>kernel/acct</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>1</LOW>
	<HIGH>99</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/kernel/acct:1</FILE>
	<DESCRIPTION>If accounting is stopped due to lack of disk space it will
be resumed when a check finds the log disk has this percentage
of space free.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Logging</SUBMENU>
	<TAB>Logging</TAB>
	<WIDGETTEXT>Suspend accounting</WIDGETTEXT>
	<CONFIGNAME>/proc/sys/kernel/acct:2</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>1</LOW>
	<HIGH>99</HIGH>
	<ELEMENT>1</ELEMENT>
	<FILE>/proc/sys/kernel/acct</FILE>
	<DESCRIPTION>When the log disk drops to this percentage of free space then
accounting is suspended.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Logging</SUBMENU>
	<TAB>Logging</TAB>
	<WIDGETTEXT>Accounting space timer</WIDGETTEXT>
	<CONFIGNAME>/proc/sys/kernel/acct:3</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>1</LOW>
	<HIGH>3600</HIGH>
	<ELEMENT>2</ELEMENT>
	<FILE>/proc/sys/kernel/acct</FILE>
	<DESCRIPTION>Controls how often in seconds the disk space is checked in order 
to resume accounting  when the disk becomes too full.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Logging</SUBMENU>
	<TAB>Logging</TAB>
	<WIDGETTEXT>Console log level</WIDGETTEXT>
	<CONFIGNAME>kernel/printk</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>0</LOW>
	<HIGH>7</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/kernel/printk</FILE>
	<DESCRIPTION>Sets the priority level needed before a message is printed to the console.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Resources</SUBMENU>
	<TAB>Resources</TAB>
	<WIDGETTEXT>Real time signals</WIDGETTEXT>
	<CONFIGNAME>kernel/rtsig-max</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>100</LOW>
	<HIGH>5000</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/kernel/rtsig-max</FILE>
	<DESCRIPTION>Some processes use real time signal queues. These queues have a
finite length to control resource usage. If you have real time
signal using applications reporting insufficient signals you may
need to adjust this.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Resources</SUBMENU>
	<TAB>Resources</TAB>
	<WIDGETTEXT>Maximum System 5 Shared Memory</WIDGETTEXT>
	<CONFIGNAME>kernel/shmall</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>1048576</LOW>
	<HIGH>2147483647</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/kernel/shmall</FILE>
	<DESCRIPTION>Set the limit on the total amount of system 5 style shared memory 
in the system. Some large database applications such as Oracle may 
require this is raised from the default.</DESCRIPTION>
	</PROCENTRY>

</PROCENTRIES>

=== codecandiescom/powertweak-0.99.5/xml/proc/memory.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROCENTRIES SYSTEM "proc.dtd">
<PROCENTRIES>

<!-- Memory Management / Core -->
	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>bdflush</SUBMENU>
	<TAB>bdflush</TAB>
	<WIDGETTEXT>Activate bdflush when % dirty</WIDGETTEXT>
	<CONFIGNAME>vm/bdflush:1</CONFIGNAME>
	<TYPE>Slider</TYPE>
	<LOW>20</LOW>
	<HIGH>90</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/vm/bdflush</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>bdflush</SUBMENU>
	<TAB>bdflush</TAB>
	<WIDGETTEXT>Dirty blocks to write per wake cycle.</WIDGETTEXT>
	<CONFIGNAME>vm/bdflush:2</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>50</LOW>
	<HIGH>1000</HIGH>
	<ELEMENT>1</ELEMENT>
	<FILE>/proc/sys/vm/bdflush</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>bdflush</SUBMENU>
	<TAB>bdflush</TAB>
	<WIDGETTEXT>Try to reclaim n buffers on refill</WIDGETTEXT>
	<CONFIGNAME>vm/bdflush:3</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>64</LOW>
	<HIGH>1024</HIGH>
	<ELEMENT>2</ELEMENT>
	<FILE>/proc/sys/vm/bdflush</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>bdflush</SUBMENU>
	<TAB>bdflush</TAB>
	<WIDGETTEXT>Dirty buffer threshold</WIDGETTEXT>
	<CONFIGNAME>vm/bdflush:4</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>256</LOW>
	<HIGH>1024</HIGH>
	<ELEMENT>3</ELEMENT>
	<FILE>/proc/sys/vm/bdflush</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>bdflush</SUBMENU>
	<TAB>bdflush</TAB>
	<WIDGETTEXT>Time to age normal buffer before flush</WIDGETTEXT>
	<CONFIGNAME>vm/bdflush:6</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>500</LOW>
	<HIGH>5000</HIGH>
	<ELEMENT>5</ELEMENT>
	<FILE>/proc/sys/vm/bdflush</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>bdflush</SUBMENU>
	<TAB>bdflush</TAB>
	<WIDGETTEXT>Time to age superblock before flush</WIDGETTEXT>
	<CONFIGNAME>vm/bdflush:7</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>100</LOW>
	<HIGH>5000</HIGH>
	<ELEMENT>6</ELEMENT>
	<FILE>/proc/sys/vm/bdflush</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Buffers/Caches</SUBMENU>
	<TAB>Buffers/Caches</TAB>
	<FRAME>Buffermem</FRAME>
	<WIDGETTEXT>Minimum percentage</WIDGETTEXT>
	<CONFIGNAME>vm/buffermem:1</CONFIGNAME>
	<TYPE>Slider</TYPE>
	<LOW>1</LOW>
	<HIGH>50</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/vm/buffermem</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Buffers/Caches</SUBMENU>
	<TAB>Buffers/Caches</TAB>
	<FRAME>Buffermem</FRAME>
	<WIDGETTEXT>Maximum percentage</WIDGETTEXT>
	<CONFIGNAME>vm/buffermem:3</CONFIGNAME>
	<TYPE>Slider</TYPE>
	<LOW>0</LOW>
	<HIGH>1024</HIGH>
	<ELEMENT>2</ELEMENT>
	<FILE>/proc/sys/vm/buffermem</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Buffers/Caches</SUBMENU>
	<TAB>Buffers/Caches</TAB>
	<FRAME>Page Cache</FRAME>
	<WIDGETTEXT>Minimum percentage</WIDGETTEXT>
	<CONFIGNAME>vm/pagecache:1</CONFIGNAME>
	<TYPE>Slider</TYPE>
	<LOW>1</LOW>
	<HIGH>50</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/vm/pagecache</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Buffers/Caches</SUBMENU>
	<TAB>Buffers/Caches</TAB>
	<FRAME>Page Cache</FRAME>
	<WIDGETTEXT>Maximum percentage</WIDGETTEXT>
	<CONFIGNAME>vm/pagecache:3</CONFIGNAME>
	<TYPE>Slider</TYPE>
	<LOW>10</LOW>
	<HIGH>90</HIGH>
	<ELEMENT>2</ELEMENT>
	<FILE>/proc/sys/vm/pagecache</FILE>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Buffers/Caches</SUBMENU>
	<TAB>Buffers/Caches</TAB>
	<FRAME>Pagetable Cache</FRAME>
	<WIDGETTEXT>Minimum</WIDGETTEXT>
	<CONFIGNAME>vm/pagetable_cache:1</CONFIGNAME>
	<TYPE>Slider</TYPE>
	<LOW>0</LOW>
	<HIGH>90</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/vm/pagetable_cache</FILE>
	<DESCRIPTION>The kernel keeps a number of page tables in a per-CPU cache.
This helps a lot on SMP systems. The cache size for each processor
will be between the min and max value.
On a low memory (&lt;16mb) single CPU system.
You can safely set these values to 0 so you don't waste memory.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Buffers/Caches</SUBMENU>
	<TAB>Buffers/Caches</TAB>
	<FRAME>Pagetable Cache</FRAME>
	<WIDGETTEXT>Maximum</WIDGETTEXT>
	<CONFIGNAME>vm/pagetable:2</CONFIGNAME>
	<TYPE>Slider</TYPE>
	<LOW>0</LOW>
	<HIGH>90</HIGH>
	<ELEMENT>1</ELEMENT>
	<FILE>/proc/sys/vm/pagetable_cache</FILE>
	<DESCRIPTION>The kernel keeps a number of page tables in a per-CPU cache.
This helps a lot on SMP systems. The cache size for each processor
will be between the min and max value.
On a low memory (&lt;16mb) single CPU system.
You can safely set these values to 0 so you don't waste memory.</DESCRIPTION>
	</PROCENTRY>

<!-- Free pages tab -->
	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Free pages</SUBMENU>
	<TAB>Free pages</TAB>
	<WIDGETTEXT>Kernel only RAM cut off</WIDGETTEXT>
	<CONFIGNAME>vm/freepages:1</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>128</LOW>
	<HIGH>1024</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/vm/freepages</FILE>
	<DESCRIPTION>When the number of free pages reaches this number, only the kernel can allocate 
more memory.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Free pages</SUBMENU>
	<TAB>Free pages</TAB>
	<WIDGETTEXT>Agressive swap cut off</WIDGETTEXT>
	<CONFIGNAME>vm/freepages:2</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>256</LOW>
	<HIGH>1024</HIGH>
	<ELEMENT>1</ELEMENT>
	<FILE>/proc/sys/vm/freepages</FILE>
	<DESCRIPTION>The kernel will attempt to swap aggressively when the free pages
goes below this limit.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Free pages</SUBMENU>
	<TAB>Free pages</TAB>
	<WIDGETTEXT>Ram to try to keep free</WIDGETTEXT>
	<CONFIGNAME>vm/freepages:3</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>384</LOW>
	<HIGH>1024</HIGH>
	<ELEMENT>2</ELEMENT>
	<FILE>/proc/sys/vm/freepages</FILE>
	<DESCRIPTION>The kernel will try to keep this amount of RAM free.
If free pages goes below this number, the kernel starts
gently swapping hoping it never has to aggressively swap.</DESCRIPTION>
	</PROCENTRY>

<!-- Swapping tab -->

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Swapping</SUBMENU>
	<TAB>Swapping</TAB>
	<WIDGETTEXT>Tries base</WIDGETTEXT>
	<CONFIGNAME>vm/kswapd:1</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>512</LOW>
	<HIGH>1024</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/vm/kswapd</FILE>
	<DESCRIPTION>The maximum number of pages kswapd tries to free in one round. 
This value is divided by 4 or 8.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Swapping</SUBMENU>
	<TAB>Swapping</TAB>
	<WIDGETTEXT>Tries min</WIDGETTEXT>
	<CONFIGNAME>vm/kswapd:2</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>16</LOW>
	<HIGH>128</HIGH>
	<ELEMENT>1</ELEMENT>
	<FILE>/proc/sys/vm/kswapd</FILE>
	<DESCRIPTION>The minimum number of times kswapd tries to free a page.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Swapping</SUBMENU>
	<TAB>Swapping</TAB>
	<WIDGETTEXT>Swap Cluster</WIDGETTEXT>
	<CONFIGNAME>vm/kswapd:3</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>32</LOW>
	<HIGH>256</HIGH>
	<ELEMENT>2</ELEMENT>
	<FILE>/proc/sys/vm/kswapd</FILE>
	<DESCRIPTION>This is the number of pages kswapd writes in one turn.
This value should be large so that kswapd does its IO in large chunks,
but not so large that it floods the request queue.</DESCRIPTION>
	</PROCENTRY>


	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Swapping</SUBMENU>
	<TAB>Swapping</TAB>
	<WIDGETTEXT>Page cluster</WIDGETTEXT>
	<CONFIGNAME>vm/page-cluster</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>1</LOW>
	<HIGH>5</HIGH>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/vm/page-cluster</FILE>
	<DESCRIPTION>This entry configures the swap readahead.
Computed value is 1 &lt;&lt; by this value.</DESCRIPTION>
	</PROCENTRY>


	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>Swapping</SUBMENU>
	<TAB>Swapping</TAB>
	<WIDGETTEXT>Overcommit Memory</WIDGETTEXT>
	<CONFIGNAME>vm/overcommit_memory</CONFIGNAME>
	<TYPE>Checkbox</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/vm/overcommit_memory</FILE>
	<DESCRIPTION>The following algorithm is used to decide if there's enough memory:
if this option is checked, then there's always enough memory.
This is a useful feature, since programs often malloc() huge amounts of
memory 'just in case', while they only use a small part of it.
Leaving this option unchecked will lead to the failure of such a
huge malloc(), when in fact the system has enough memory for the program to run.

On the other hand, enabling this feature can cause you to run out of
memory and thrash the system to death, so large and/or important servers
will want to set this disabled.</DESCRIPTION>
	</PROCENTRY>

</PROCENTRIES>

=== codecandiescom/powertweak-0.99.5/xml/proc/kernel25.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROCENTRIES SYSTEM "proc.dtd">
<PROCENTRIES>

<!-- Virtual Memory / bdflush -->
	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>bdflush</SUBMENU>
	<TAB>bdflush</TAB>
	<WIDGETTEXT>Dirty Ration</WIDGETTEXT>
	<CONFIGNAME>vm/dirty_ratio:0</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>0</LOW>
	<HIGH>100</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/vm/dirty_ratio</FILE>
	<DESCRIPTION>Contains, as a percentage of total system memory, the number of pages at which a process which is generating disk writes will itself start writing out dirty data.  </DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>bdflush</SUBMENU>
	<TAB>bdflush</TAB>
	<WIDGETTEXT>Dirty Writeback Centisecs</WIDGETTEXT>
	<CONFIGNAME>vm/dirty_writeback_centisecs:0</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>50</LOW>
	<HIGH>10000000</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/vm/dirty_writeback_centisecs</FILE>
	<DESCRIPTION>The pdflush writeback daemons will periodically wake up and write `old' data out to disk.  This tunable expresses the interval between those wakeups, in 100'ths of a second.  </DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Virtual Memory</MENU>
	<SUBMENU>bdflush</SUBMENU>
	<TAB>bdflush</TAB>
	<WIDGETTEXT>Dirty Expire Centisecs</WIDGETTEXT>
	<CONFIGNAME>vm/dirty_expire_centisecs:0</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>10</LOW>
	<HIGH>10000000</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/vm/dirty_expire_centisecs</FILE>
	<DESCRIPTION>This tunable is used to define when dirty data is old enough to be eligible for writeout by the pdflush daemons.  It is expressed in 100'ths of a second.  Data which has been dirty in-memory for longer than this interval will be written out next time a pdflush daemon wakes up.  </DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Kernel</MENU>
	<SUBMENU>Logging</SUBMENU>
	<TAB>Core</TAB>
	<WIDGETTEXT>Core Filename Pattern</WIDGETTEXT>
	<CONFIGNAME>kernel/core_pattern</CONFIGNAME>
	<TYPE>INFOSTRING</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/proc/sys/kernel/core_pattern</FILE>
	<DESCRIPTION>- 2.5 offers you the ability to configure the way core files are named through a /proc/sys/kernel/core_pattern file.  You can use various format identifiers in this name to affect how the core dump is named.  %p - insert pid into filename %u - insert current uid into filename %g - insert current gid into filename %s - insert signal that caused the coredump into the filename %t - insert UNIX time that the coredump occurred into filename %h - insert hostname where the coredump happened into filename %e - insert coredumping executable name into filename You should ensure that the string does not exceed 64 bytes.  - Threaded coredumps is now supported.</DESCRIPTION>
	</PROCENTRY>

</PROCENTRIES>

=== codecandiescom/powertweak-0.99.5/xml/proc/combotest.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROCENTRIES SYSTEM "proc.dtd">
<PROCENTRIES>

<!-- Network -->
	<PROCENTRY>
	<MENU>Test</MENU>
	<SUBMENU>Test</SUBMENU>
	<TAB>Test</TAB>
	<GROUP>TestRadioButton</GROUP>
	<WIDGETTEXT>TestRadioButton item 1</WIDGETTEXT>
	<CONFIGNAME>COMBO1</CONFIGNAME>
	<TYPE>RadioButton</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/tmp/1</FILE>
	<DESCRIPTION>I dunno what this does </DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>Test</MENU>
	<SUBMENU>Test</SUBMENU>
	<TAB>Test</TAB>
	<GROUP>TestRadioButton</GROUP>
	<WIDGETTEXT>TestRadioButton item 2</WIDGETTEXT>
	<CONFIGNAME>COMBO2</CONFIGNAME>
	<TYPE>RadioButton</TYPE>
	<ELEMENT>-1</ELEMENT>
	<FILE>/tmp/1</FILE>
	<DESCRIPTION>I dunno what this does </DESCRIPTION>
	</PROCENTRY>



</PROCENTRIES>

=== codecandiescom/powertweak-0.99.5/xml/proc/filesystems.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROCENTRIES SYSTEM "proc.dtd">
<PROCENTRIES>

<!-- Filesystems / Core -->


	<PROCENTRY>
	<MENU>VFS Subsystem</MENU>
	<SUBMENU>Core</SUBMENU>
	<TAB>File system Core</TAB>
	<WIDGETTEXT>dquota-max</WIDGETTEXT>
	<CONFIGNAME>fs/dquot-max</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>0</LOW>
	<HIGH>8192</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/fs/dquot-max</FILE>
	<DESCRIPTION>Holds the maximum number of cached disk quota entries.
Should be increased if you have many simultaneous users.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>VFS Subsystem</MENU>
	<SUBMENU>Core</SUBMENU>
	<TAB>File system Core</TAB>
	<WIDGETTEXT>file-max</WIDGETTEXT>
	<CONFIGNAME>fs/file-max</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>0</LOW>
	<HIGH>16384</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/fs/file-max</FILE>
	<DESCRIPTION>The value in file-max denotes the maximum number of file handles
that the Linux kernel will allocate. When you get a lot of error
messages about running out of file handles, you might want to raise
this limit. The default value is 4096.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>VFS Subsystem</MENU>
	<SUBMENU>Core</SUBMENU>
	<TAB>File system Core</TAB>
	<WIDGETTEXT>inode-max</WIDGETTEXT>
	<CONFIGNAME>fs/inode-max</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>0</LOW>
	<HIGH>65535</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/fs/inode-max</FILE>
	<DESCRIPTION>The maximum number of inodes possible to use.
You should set this to two or three times higher than file-max.</DESCRIPTION>
	</PROCENTRY>

	<PROCENTRY>
	<MENU>VFS Subsystem</MENU>
	<SUBMENU>Core</SUBMENU>
	<TAB>File system Core</TAB>
	<WIDGETTEXT>super-max</WIDGETTEXT>
	<CONFIGNAME>fs/super-max</CONFIGNAME>
	<TYPE>Spinbutton</TYPE>
	<LOW>0</LOW>
	<HIGH>1024</HIGH>
	<ELEMENT>0</ELEMENT>
	<FILE>/proc/sys/fs/super-max</FILE>
	<DESCRIPTION>The maximum number of superblocks that may be used.
One superblock is used each time you mount a filesystem.</DESCRIPTION>
	</PROCENTRY>
</PROCENTRIES>
