=== codecandiescom/powertweak-0.99.5/xml/profile/profile.dtd
<!ELEMENT PROFILE ANY>
<!ELEMENT SETTING (CONFIGNAME,OPERATOR,VALUE)>
<!ELEMENT CONFIGNAME (#PCDATA)>
<!ELEMENT OPERATOR (#PCDATA)>
<!ELEMENT VALUE (#PCDATA)>

=== codecandiescom/powertweak-0.99.5/xml/profile/laptop.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROFILE SYSTEM "../profile.dtd">
<PROFILE>
	<SETTING>
	<CONFIGNAME>vm/bdflush:6</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>6000</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>vm/bdflush:1</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>60</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>PMMX_LOWPOWER</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>PMMX_DISABLE_AUTOHALT</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>VAIO_LCD_BRIGHTNESS</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>255</VALUE>
	</SETTING>
</PROFILE>

=== codecandiescom/powertweak-0.99.5/xml/profile/gigabit.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROFILE SYSTEM "../profile.dtd">
<PROFILE>
	<SETTING>
	<CONFIGNAME>net/core/rmem_default</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>262144</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/core/wmem_default</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>262144</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/core/tcp_wmem</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>262144</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/core/tcp_rmem</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>262144</VALUE>
	</SETTING>

</PROFILE>

=== codecandiescom/powertweak-0.99.5/xml/profile/tuxwebserv.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROFILE SYSTEM "../profile.dtd">
<PROFILE>

<!-- Profile for the TUX 1.0x webserver. Only use this for a BIG box -->
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_syncookies</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>0</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_ecn</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>0</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>kernel/panic</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/ip_forward</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>0</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/conf/all/rp_filter</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_timestamps</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>0</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_sack</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>0</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_window_scaling</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>0</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_max_tw_buckets</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>2000000</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_mem/0</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>100000000</VALUE>
	</SETTING>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_mem/1</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>100000000</VALUE>
	</SETTING>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_mem/2</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>100000000</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_wmem/0</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>100000000</VALUE>
	</SETTING>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_wmem/1</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>100000000</VALUE>
	</SETTING>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_wmem/2</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>100000000</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_rmem/0</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>30000000</VALUE>
	</SETTING>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_rmem/1</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>30000000</VALUE>
	</SETTING>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_rmem/2</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>30000000</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>net/core/hot_list_length</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>102400</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/core/optmem_max</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>10000000</VALUE>
	</SETTING>



	<SETTING>
	<CONFIGNAME>net/core/rmem_max</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>102485760</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>net/core/wmem_max</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>102485760</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>net/core/rmem_default</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>102485760</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>net/core/wmem_default</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>102485760</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>fs/file-max</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>40960</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>vm/bdflush:1</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>100</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>vm/bdflush:2</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>5000</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>vm/bdflush:3</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>640</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>vm/bdflush:4</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>2560</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>vm/bdflush:5</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>150</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>vm/bdflush:6</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>30000</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>vm/bdflush:7</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>5000</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>vm/bdflush:8</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>1884</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>vm/bdflush:9</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>2</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>vm/freepages:1</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>16384</VALUE>
	</SETTING>


	<SETTING>
	<CONFIGNAME>vm/freepages:2</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>32768</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>vm/freepages:3</CONFIGNAME>
	<OPERATOR>eq</OPERATOR>
	<VALUE>65536</VALUE>
	</SETTING>

</PROFILE>

=== codecandiescom/powertweak-0.99.5/xml/profile/network-compat.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROFILE SYSTEM "../profile.dtd">
<PROFILE>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_syncookies</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_ecn</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>0</VALUE>
	</SETTING>
</PROFILE>

=== codecandiescom/powertweak-0.99.5/xml/profile/webserver.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROFILE SYSTEM "../profile.dtd">
<PROFILE>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_syncookies</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_ecn</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>0</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>kernel/panic</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>fs/file_max</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>10240</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>fs/inode_max</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>30720</VALUE>
	</SETTING>

</PROFILE>

=== codecandiescom/powertweak-0.99.5/xml/profile/router.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROFILE SYSTEM "../profile.dtd">
<PROFILE>
	<SETTING>
	<CONFIGNAME>net/ipv4/tcp_syncookies/CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>kernel/panic</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/ip_dynaddr</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/ip_always_defrag</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>0</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/ip_forward</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/route/mtu_expires</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>1800</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>vm/freepages:3</CONFIGNAME>
	<OPERATOR>geq</OPERATOR>
	<VALUE>512</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>NET_TCPIP_DEV_PROXY_ARPeth0</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>NET_TCPIP_DEV_ACCEPT_RP_FILTEReth0</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>1</VALUE>
	</SETTING>

</PROFILE>

=== codecandiescom/powertweak-0.99.5/xml/profile/nfs.xml
<?xml version = "1.0" encoding ="UTF-8" standalone = "no"?>
<!DOCTYPE PROFILE SYSTEM "../profile.dtd">
<PROFILE>
	<SETTING>
	<CONFIGNAME>net/ipv4/ipfrag_low_thresh</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>262144</VALUE>
	</SETTING>

	<SETTING>
	<CONFIGNAME>net/ipv4/ipfrag_high_thresh</CONFIGNAME>
	<OPERATOR>=</OPERATOR>
	<VALUE>524288</VALUE>
	</SETTING>
</PROFILE>
